export const accountSections = [
  'overview',
  'orders',
  'nearby',
  'addresses',
  'wishlist',
  'subscriptions',
  'wallet',
  'rewards',
  'reviews',
  'returns',
  'settings',
] as const;
export const adminSections = [
  'overview',
  'farmer-onboarding',
  'tenants',
  'users',
  'products',
  'categories',
  'orders',
  'inventory',
  'settlements',
  'delivery-zones',
  'warehouses',
  'payments',
  'content',
  'promotions',
  'reviews',
  'support',
  'analytics',
  'settings',
] as const;
export const farmerSections = [
  'overview',
  'list-harvest',
  'products',
  'orders',
  'inventory',
  'delivery-zone',
  'customers',
  'payments',
  'payouts',
  'certifications',
  'team',
  'store-profile',
] as const;
